# =========================
# Application Info
# =========================
spring.application.name=sdp-backend

# =========================
# Mail Config (Gmail SMTP)
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=swiftyyy.co@gmail.com
spring.mail.password=ndrh mqlb ycbx cekl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# =========================
# PostgreSQL Database Config
# =========================
spring.datasource.url=jdbc:postgresql://swifty-16485.j77.aws-ap-south-1.cockroachlabs.cloud:26257/defaultdb
spring.datasource.password=gI_65zusLIAUMHPWjiFRtw
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (Hibernate) settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
